# top level project rules for the msm8960_virtio project
#
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := msm8960

MODULES += app/aboot
#MODULES += app/shell

ifeq ($(TARGET_BUILD_VARIANT),user)
DEBUG := 0
else
DEBUG := 1
endif

ENABLE_LEGACY_DISPLAY_SUPPORT := 1
DEFINES += WITH_DEBUG_LOG_BUF=1

DEFINES += DISPLAY_TYPE_MDSS=1
#DEFINES += DISPLAY_TYPE_MIPI=1
#DEFINES += DISPLAY_TYPE_HDMI=0

#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
DEFINES += WITH_DEBUG_FBCON=1
ENABLE_THUMB := false
